{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameThumbnails" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "oc.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "oc.affinity" $ | nindent 6 }}
      {{- include "oc.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- if and $.Values.services.thumbnails.persistence.enabled $.Values.services.thumbnails.persistence.chownInitContainer }}
      initContainers:
        - name: init-chown-data
          {{- include "oc.initContainerImage" $ | nindent 10 }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          {{- include "oc.initChownDataCommand" $ | nindent 10 }}
          volumeMounts:
          - name: {{ include "oc.persistence.dataVolumeName" . }}
            mountPath: /var/lib/opencloud
      {{ end }}
      {{- include "oc.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "oc.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "oc.image" $ | nindent 10 }}
          command: ["opencloud"]
          args: ["thumbnails", "server"]
          {{- include "oc.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "oc.serviceRegistry" . | nindent 12 }}
            {{- include "oc.cors" . |nindent 12 }}

            - name: THUMBNAILS_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: THUMBNAILS_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: THUMBNAILS_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: THUMBNAILS_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: THUMBNAILS_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: THUMBNAILS_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: THUMBNAILS_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: THUMBNAILS_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: THUMBNAILS_GRPC_ADDR
              value: 0.0.0.0:9185
            - name: THUMBNAILS_HTTP_ADDR
              value: 0.0.0.0:9186
            - name: THUMBNAILS_DEBUG_ADDR
              value: 0.0.0.0:9189

            - name: THUMBNAILS_DATA_ENDPOINT
              value: http://{{ .appName }}:9186/thumbnails/data

            - name: THUMBNAILS_MAX_CONCURRENT_REQUESTS
              value: {{ .Values.services.thumbnails.quota.maxConcurrencyRequests | quote }}
            - name: THUMBNAILS_MAX_INPUT_IMAGE_FILE_SIZE
              value: {{ .Values.services.thumbnails.quota.maxFileSize | quote }}
            - name: THUMBNAILS_MAX_INPUT_WIDTH
              value: {{ .Values.services.thumbnails.quota.maxInputWidth | quote }}
            - name: THUMBNAILS_MAX_INPUT_HEIGHT
              value: {{ .Values.services.thumbnails.quota.maxInputHeight | quote }}

            - name: THUMBNAILS_WEBDAVSOURCE_INSECURE
              value: {{ .Values.insecure.ocHttpApiInsecure | quote }}

            - name: THUMBNAILS_CS3SOURCE_INSECURE
              value: {{ .Values.insecure.ocHttpApiInsecure | quote }}

            - name: THUMBNAILS_TRANSFER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.thumbnailsSecret" . }}
                  key: thumbnails-transfer-secret

            {{- include "oc.caEnv" $ | nindent 12}}

          {{- include "oc.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: grpc
              containerPort: 9185
            - name: http
              containerPort: 9186
            - name: metrics-debug
              containerPort: 9189

          volumeMounts:
            - name: {{ include "oc.persistence.dataVolumeName" . }}
              mountPath: /var/lib/opencloud
            {{- include "oc.caPath" $ | nindent 12}}

      {{- include "oc.imagePullSecrets" $ | nindent 6 }}
      volumes:
        {{- include "oc.caVolume" $ | nindent 8}}
        {{- include "oc.persistence.dataVolume" . | nindent 8 }}
