{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameThumbnails" "appNameSuffix" "") -}}
{{- $_ := set . "autoscaling" (default (default (dict) .Values.autoscaling) .Values.services.thumbnails.autoscaling) -}}
{{ include "oc.hpa" . }}
