{{- if not .Values.secretRefs.thumbnailsSecretRef }}
{{- $params := (dict)}}
{{- $_ := set $params "thumbnails-transfer-secret" (randAlphaNum 30) }}
{{- include "oc.secret" (dict "scope" . "name" "thumbnails-transfer-secret" "params" $params)}}
{{- end }}
