{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNamePostprocessing" "appNameSuffix" "") -}}
{{- $_ := set . "autoscaling" (default (default (dict) .Values.autoscaling) .Values.services.postprocessing.autoscaling) -}}
{{ include "oc.hpa" . }}
