{{ if .Values.features.policies.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNamePolicies" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .appName }}
  namespace: {{ template "oc.namespace" . }}
  labels:
    {{- include "oc.labels" . | nindent 4 }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "oc.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" true) | nindent 4 }}
    spec:
      {{- include "oc.affinity" $ | nindent 6 }}
      {{- include "oc.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "oc.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "oc.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "oc.image" $ | nindent 10 }}
          command: ["opencloud"]
          args: ["policies", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            {{- include "oc.serviceRegistry" . | nindent 12 }}
            {{- include "oc.events" . | nindent 12 }}

            - name: POLICIES_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: POLICIES_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: POLICIES_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}
            - name: POLICIES_GRPC_ADDR
              value: 0.0.0.0:9125
            - name: POLICIES_ENGINE_TIMEOUT
              value: {{ .Values.features.policies.engineTimeout | quote }}
            # We currently don't support enforcing policies as a postprocessing step.
            # See https://github.com/opencloud/enterprise/issues/5919
            # - name: POLICIES_POSTPROCESSING_QUERY
            #   value: "data.postprocessing.granted"

            - name: POLICIES_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: POLICIES_DEBUG_ADDR
              value: 0.0.0.0:9129

            {{- include "oc.caEnv" $ | nindent 12}}

          {{- include "oc.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: grpc
              containerPort: 9125
            - name: metrics-debug
              containerPort: 9129

          volumeMounts:
            - name: messaging-system-ca
              mountPath: /etc/opencloud/messaging-system-ca
              readOnly: true
            - name: configs
              mountPath: /etc/opencloud
            {{- include "oc.caPath" $ | nindent 12}}

      {{- include "oc.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: messaging-system-ca
          {{ if and (.Values.messagingSystem.external.enabled) (not .Values.messagingSystem.external.tls.certTrusted) }}
          secret:
            secretName: {{ include "secrets.messagingSystemCASecret" . }}
          {{ else }}
          emptyDir: {}
          {{ end }}
        - name: configs
          configMap:
            name: {{ .appName }}-config
        {{- include "oc.caVolume" $ | nindent 8}}
{{ end }}
