{{ if .Values.features.policies.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNamePolicies" "appNameSuffix" "") -}}
{{- $_ := set . "autoscaling" (default (default (dict) .Values.autoscaling) .Values.services.policies.autoscaling) -}}
{{ include "oc.hpa" . }}
{{ end }}
