{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameOnlyOffice" "appNameSuffix" "") -}}
{{- if .Values.onlyoffice.enabled }}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  replicas: 1
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      containers:
        - name: onlyoffice
          image: {{ .Values.onlyoffice.repository }}:{{ .Values.onlyoffice.tag | default "8.2.2" }}
          imagePullPolicy: {{ .Values.onlyoffice.pullPolicy | default "IfNotPresent" }}
          command: ["/bin/sh", "/entrypoint-override.sh"]
          env:
            - name: WOPI_ENABLED
              value: "{{ .Values.onlyoffice.wopi.enabled }}"
            - name: USE_UNAUTHORIZED_STORAGE
              value: "{{ .Values.onlyoffice.useUnauthorizedStorage }}"
            - name: DB_TYPE
              value: "{{ .Values.onlyoffice.config.coAuthoring.sql.type | default "postgres" }}"
            - name: DB_HOST
              value: "{{ .Values.onlyoffice.config.coAuthoring.sql.dbHost | default "localhost" }}"
            - name: DB_PORT
              value: "{{ .Values.onlyoffice.config.coAuthoring.sql.dbPort | default "5432" }}"
            - name: DB_NAME
              value: "{{ .Values.onlyoffice.config.coAuthoring.sql.dbName | default "onlyoffice" }}"
            - name: DB_USER
              value: "{{ .Values.onlyoffice.config.coAuthoring.sql.dbUser | default "onlyoffice" }}"
            - name: JWT_SECRET
              value: "{{ .Values.onlyoffice.config.coAuthoring.secret.session | default "B8LjkNqGxn6gf8bkuBUiMwyuCFwFddnu" }}"
            - name: JWT_HEADER
              value: "Authorization"
            - name: AMQP_URI
              value: "{{ .Values.onlyoffice.config.rabbitmq.url | default "amqp://guest:guest@localhost" }}"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          volumeMounts:
            - name: onlyoffice-config
              mountPath: /entrypoint-override.sh
              subPath: entrypoint-override.sh
            - name: onlyoffice-config
              mountPath: /etc/onlyoffice/documentserver/local.dist.json
              subPath: local.json
            {{- if .Values.onlyoffice.persistence.enabled }}
            - name: onlyoffice-data
              mountPath: /var/lib/onlyoffice
            {{- end }}
          resources:
            {{- toYaml .Values.onlyoffice.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /hosting/discovery
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /hosting/discovery
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: onlyoffice-config
          configMap:
            name: {{ .appName }}-config
        {{- if .Values.onlyoffice.persistence.enabled }}
        - name: onlyoffice-data
          persistentVolumeClaim:
            claimName: {{ .appName }}-data
        {{- end }}
{{- end }}
