{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameOnlyOffice" "appNameSuffix" "") -}}
{{- if and .Values.onlyoffice.enabled .Values.onlyoffice.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .appName }}-data
  namespace: {{ template "oc.namespace" . }}
  annotations:
  labels:
    app: {{ .appName }}
    oc-metrics: enabled
    {{- include "oc.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.onlyoffice.persistence.size | default "5Gi" }}
{{- end }}
