{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameOnlyOffice" "appNameSuffix" "") -}}
{{- if .Values.onlyoffice.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    oc-metrics: enabled
    {{- include "oc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ .appName }}
{{- end }}
