{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameMinio" "appNameSuffix" "") -}}
{{- if and .Values.minio.enabled .Values.gateway.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    oc-metrics: enabled
    {{- include "oc.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.httproute.gateway.name }}
      namespace: {{ .Values.gateway.httproute.gateway.namespace }}
      sectionName: oc-minio-https
  hostnames:
    - {{ .Values.minio.domain }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .appName }}
          port: 9000
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-minio-console
  labels:
    {{- include "oc.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  parentRefs:
    - name: {{ .Values.gateway.httproute.gateway.name }}
      namespace: {{ .Values.gateway.httproute.gateway.namespace }}
      sectionName: oc-minio-console-https
  hostnames:
    - console.{{ .Values.minio.domain }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .appName }}
          port: 9001
{{- end }}
