{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameMinio" "appNameSuffix" "") -}}
{{- if .Values.minio.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .appName }}
  labels:
    {{- include "oc.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.config.persistence.size }}
{{- end }}
