# apiVersion: v1
# kind: Pod
# metadata:
#   name: s3-test-pod
# spec:
#   containers:
#   - name: s3-test
#     image: minio/mc
#     command: ["sleep", "infinity"]
#     volumeMounts:
#     - name: s3-credentials
#       mountPath: /root/.aws
#       readOnly: true
#   volumes:
#   - name: s3-credentials
#     secret:
#       secretName: s3secret
#       items:
#       - key: accessKey
#         path: credentials
