{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameAppRegistry" "appNameSuffix" "") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .appName }}-config
  namespace: {{ template "oc.namespace" . }}
  labels:
    {{- include "oc.labels" . | nindent 4 }}
data:
  app-registry.yaml: |
    ---
{{- if gt (len .Values.features.appsIntegration.mimetypes) 0 }}
    app_registry:
      mimetypes:
{{- toYaml .Values.features.appsIntegration.mimetypes | nindent 6 }}
{{- end }}
