{{- if not .Values.messagingSystem.external.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameNats" "appNameSuffix" "") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    oc-metrics: enabled
    {{- include "oc.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .appName }}
  ports:
    - name: nats
      port: 9233
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol.nats | quote}}
    - name: metrics-debug
      port: 9234
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol.http | quote}}
{{- end }}
