# TODO: move to ConfigMap
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-config-pvc
  labels:
    app: opencloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
