apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: opencloud
spec:
  selector:
    app: opencloud
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9200