apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-data-pvc
  annotations:
    # prevent data pvc from being uninstalled
    helm.sh/resource-policy: "keep"
  labels:
    app: opencloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvcSize }}
