{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameUsers" "appNameSuffix" "") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    oc-metrics: enabled
    {{- include "oc.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .appName }}
  ports:
    - name: grpc
      port: 9144
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol.grpc | quote}}
    - name: metrics-debug
      port: 9145
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol.http | quote}}
