apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2025-06-29T13:44:31Z"
  creationTimestamp: "2025-06-29T14:30:44Z"
  generateName: collabora-79c6578c7d-
  labels:
    app: collabora
    app.kubernetes.io/instance: opencloud-helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opencloud-full
    app.kubernetes.io/version: 3.0.0
    helm.sh/chart: opencloud-full-3.0.0
    pod-template-hash: 79c6578c7d
  name: collabora-79c6578c7d-79t45
  namespace: opencloud-helm
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: collabora-79c6578c7d
    uid: 9f7f814c-51b9-4e10-9cc0-8c5090c21c15
  resourceVersion: "16610306"
  uid: 3ba6bb02-3e95-4d9c-b357-04925f10c85b
spec:
  containers:
  - args:
    - coolconfig generate-proof-key && /start-collabora-online.sh
    command:
    - /bin/bash
    - -c
    env:
    - name: aliasgroup1
      value: http://collaboration-collabora:9300,https://collabora.opencloud.test,http://collaboration-collabora.opencloud-helm.svc.cluster.local:9300
    - name: DONT_GEN_SSL_CERT
      value: "YES"
    - name: extra_params
      value: |
        --o:ssl.enable=false \
        --o:ssl.ssl_verification=false \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=cloud.opencloud.test
    - name: username
      value: admin
    - name: password
      value: admin
    image: collabora/code:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /hosting/discovery
        port: http
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: collabora
    ports:
    - containerPort: 9980
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /hosting/discovery
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      capabilities:
        add:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mtldj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: talos-mec-lba
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-mtldj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-29T14:30:46Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-06-29T14:30:44Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-29T14:30:44Z"
    message: 'containers with unready status: [collabora]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-29T14:30:44Z"
    message: 'containers with unready status: [collabora]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-29T14:30:44Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://3ed8ae043c50246efe4a1d59c26fbc992cae064b16b572aeae7913899b7086ff
    image: docker.io/collabora/code:latest
    imageID: docker.io/collabora/code@sha256:494ea00ed33e4149698e8995a1fb101400f581810fb86a864dc671a734fdb666
    lastState: {}
    name: collabora
    ready: false
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-06-29T14:30:45Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mtldj
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.178.79
  hostIPs:
  - ip: 192.168.178.79
  phase: Running
  podIP: 10.244.2.158
  podIPs:
  - ip: 10.244.2.158
  qosClass: Burstable
  startTime: "2025-06-29T14:30:44Z"
