{{- if .Values.features.emailNotifications.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameNotifications" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "oc.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "oc.affinity" $ | nindent 6 }}
      {{- include "oc.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "oc.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "oc.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "oc.image" $ | nindent 10 }}
          command: ["opencloud"]
          args: ["notifications", "server"]
          {{- include "oc.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "oc.serviceRegistry" . | nindent 12 }}
            {{- include "oc.events" . | nindent 12 }}
            {{- include "oc.persistentStore" . | nindent 12 }}

            - name: OC_DEFAULT_LANGUAGE
              value: {{ default "en" .Values.features.language.default | quote }}

            - name: NOTIFICATIONS_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: NOTIFICATIONS_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: NOTIFICATIONS_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            # Tracing not yet implemented: https://github.com/opencloud/opencloud/issues/6175
            - name: NOTIFICATIONS_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: NOTIFICATIONS_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: NOTIFICATIONS_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: NOTIFICATIONS_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: NOTIFICATIONS_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: NOTIFICATIONS_DEBUG_ADDR
              value: 0.0.0.0:9174

            - name: NOTIFICATIONS_SMTP_HOST
              value: {{ .Values.features.emailNotifications.smtp.host | quote }}
            - name: NOTIFICATIONS_SMTP_PORT
              value: {{ .Values.features.emailNotifications.smtp.port | quote }}
            - name: NOTIFICATIONS_SMTP_SENDER
              value: {{ .Values.features.emailNotifications.smtp.sender | quote }}
            - name: NOTIFICATIONS_SMTP_AUTHENTICATION
              value: {{ .Values.features.emailNotifications.smtp.authentication | quote }}
            - name: NOTIFICATIONS_SMTP_ENCRYPTION
              value: {{ .Values.features.emailNotifications.smtp.encryption | quote }}

            {{- if ne .Values.features.emailNotifications.smtp.authentication "none" }}
            - name: NOTIFICATIONS_SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.notificationsSMTPSecret" . }}
                  key: smtp-username

            - name: NOTIFICATIONS_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.notificationsSMTPSecret" . }}
                  key: smtp-password
            {{- end }}

            - name: NOTIFICATIONS_WEB_UI_URL
              value: "https://{{ .Values.externalDomain }}"

            - name: NOTIFICATIONS_SERVICE_ACCOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "config.authService" . }}
                  key: service-account-id
            - name: NOTIFICATIONS_SERVICE_ACCOUNT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.serviceAccountSecret" . }}
                  key: service-account-secret

            {{- if .Values.features.emailNotifications.branding.enabled }}
            # Mail theming
            - name: NOTIFICATIONS_EMAIL_TEMPLATE_PATH
              value: /etc/opencloud/notifications
            {{- end }}

            {{- include "oc.caEnv" $ | nindent 12}}

          {{- include "oc.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}
          ports:
            - name: metrics-debug
              containerPort: 9174

          volumeMounts:
            - name: messaging-system-ca
              mountPath: /etc/opencloud/messaging-system-ca
              readOnly: true
            {{- if .Values.features.emailNotifications.branding.enabled }}
            - name: text-mail-templates
              mountPath: /etc/opencloud/notifications/templates/text
            - name: html-mail-templates
              mountPath: /etc/opencloud/notifications/templates/html
            - name: html-mail-images
              mountPath: /etc/opencloud/notifications/templates/html/img
            {{- end }}
            {{- include "oc.caPath" $ | nindent 12}}

      {{- include "oc.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: messaging-system-ca
          {{ if and (.Values.messagingSystem.external.enabled) (not .Values.messagingSystem.external.tls.certTrusted) }}
          secret:
            secretName: {{ include "secrets.messagingSystemCASecret" . }}
          {{ else }}
          emptyDir: {}
          {{ end }}
        {{- if .Values.features.emailNotifications.branding.enabled }}
        - name: text-mail-templates
          configMap:
            name: {{ .Values.features.emailNotifications.branding.textMailTemplatesConfigRef | quote }}
        - name: html-mail-templates
          configMap:
            name: {{ .Values.features.emailNotifications.branding.htmlMailTemplatesConfigRef | quote }}
        - name: html-mail-images
          configMap:
            name: {{ .Values.features.emailNotifications.branding.htmlMailImagesConfigRef | quote }}
            optional: true
        {{- end }}
        {{- include "oc.caVolume" $ | nindent 8}}
{{- end }}
