apiVersion: v1
kind: Namespace
metadata:
  name: clamav
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opencloud-config
  namespace: clamav
data:
  ###############################################################################
  # Persistence StorageClass and AccessModes (global defaults)
  ###############################################################################
  PERSISTENCE_STORAGE_CLASS_NAME: ""
  # Comma-separated for runtime to split into a list, e.g. "ReadWriteMany" or "ReadWriteOnce,ReadOnlyMany"
  PERSISTENCE_ACCESS_MODES: "ReadWriteOnce"

  ###############################################################################
  # ClamAV Configuration
  ###############################################################################
  CLAMAV_REPLICA_COUNT: "1"
  CLAMAV_RESOURCES_LIMITS_CPU: "500m"
  CLAMAV_RESOURCES_LIMITS_MEMORY: "512Mi"
  CLAMAV_RESOURCES_REQUESTS_CPU: "250m"
  CLAMAV_RESOURCES_REQUESTS_MEMORY: "256Mi"
  CLAMAV_PERSISTENCE_SIZE: "10Gi"
  CLAMAV_FRESHCLAM_IMAGE_TAG: "1.4.0"
  CLAMAV_CLAMD_IMAGE_TAG: "1.4.0"
  CLAMAV_ICAP_IMAGE_TAG: "0.5.10"
  CLAMAV_ICAP_IMAGE_REPOSITORY: "bmi/opendesk/components/platform-development/images/clamav-icap"
  CLAMAV_ICAP_IMAGE_REGISTRY: "registry.opencode.de"
  CLAMAV_ICAP_CLAMD_HOST: "clamav-clamd"
  CLAMAV_MILTER_CLAMD_HOST: "clamav-clamd"
