# Service account clamav namespace
# 1) ServiceAccount — Flux will impersonate this
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: clamav
---
# 2) Role — full power *inside* that namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clamav-role
  namespace: clamav
rules:
  - apiGroups:   ["*"]     # core & all groups
    resources:   ["*"]     # every namespaced resource
    verbs:       ["*"]     # get, list, create, delete, …
---
# 3) RoleBinding — ties the Role to the SA
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clamav-rolebinding
  namespace: clamav
subjects:
  - kind:      ServiceAccount
    name:      flux
    namespace: clamav
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:     Role
  name:     clamav-role
