apiVersion: v1
kind: Namespace
metadata:
  name: openldap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opencloud-config
  namespace: openldap
data:
  ###############################################################################
  # LDAP Configuration
  ###############################################################################
  LDAP_GLOBAL_DOMAIN: "opencloud.eu"
  OPENLDAP_LTB_PASSWD_ENABLED: "false"
  OPENLDAP_REPLICATION_ENABLED: "false"
  OPENLDAP_REPLICA_COUNT: "1"
