{{ if .Values.features.virusscan.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameAntivirus" "appNameSuffix" "") -}}
{{- $_ := set . "autoscaling" (default (default (dict) .Values.autoscaling) .Values.services.antivirus.autoscaling) -}}
{{ include "oc.hpa" . }}
{{- end }}
