{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameOcs" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "oc.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "oc.affinity" $ | nindent 6 }}
      {{- include "oc.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "oc.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "oc.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "oc.image" $ | nindent 10 }}
          command: ["opencloud"]
          args: ["ocs", "server"]
          {{- include "oc.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "oc.serviceRegistry" . | nindent 12 }}
            {{- include "oc.cors" . |nindent 12 }}
            {{- include "oc.cacheStore" . | nindent 12 }}

            - name: OCS_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: OCS_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: OCS_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: OCS_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: OCS_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: OCS_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: OCS_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: OCS_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: OCS_HTTP_ADDR
              value: 0.0.0.0:9110
            - name: OCS_DEBUG_ADDR
              value: 0.0.0.0:9114

            - name: OCS_IDM_ADDRESS
            {{ if not .Values.features.externalUserManagement.enabled }}
              value: "https://{{ .Values.externalDomain }}"
            {{ else }}
              value: {{ .Values.features.externalUserManagement.oidc.issuerURI | quote }}
            {{ end }}

            - name: OCS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.jwtSecret" . }}
                  key: jwt-secret

            {{- include "oc.caEnv" $ | nindent 12}}

          {{- include "oc.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9110
            - name: metrics-debug
              containerPort: 9114

          volumeMounts:
            {{- include "oc.caPath" $ | nindent 12}}

      {{- include "oc.imagePullSecrets" $ | nindent 6 }}
      volumes:
        {{- include "oc.caVolume" $ | nindent 8}}
