{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameCollabora" "appNameSuffix" "") -}}
{{- if .Values.collabora.enabled }}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . | nindent 0 }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  replicas: 1
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      containers:
        - name: collabora
          image: {{ .Values.collabora.repository }}:{{ .Values.collabora.tag | default "latest" }}
          imagePullPolicy: {{ .Values.collabora.pullPolicy | default "IfNotPresent" }}
          command: ['/bin/bash', '-c']
          args:
            - 'coolconfig generate-proof-key && /start-collabora-online.sh'
          env:
            - name: aliasgroup1
              value: 'http://collaboration-collabora:9300,https://{{ .Values.collabora.domain }},http://collaboration-collabora.{{ template "oc.namespace" $ }}.svc.cluster.local:9300'
            - name: DONT_GEN_SSL_CERT
              value: "YES"
            - name: extra_params
              value: |
                --o:ssl.enable={{ .Values.collabora.ssl.enabled }} \
                --o:ssl.ssl_verification={{ .Values.collabora.ssl.verification }} \
                --o:ssl.termination=true \
                --o:welcome.enable=false \
                --o:net.frame_ancestors={{ .Values.externalDomain }}
            - name: username
              value: "{{ .Values.collabora.admin.user | default "admin" }}"
            - name: password
              value: "{{ .Values.collabora.admin.password | default "admin" }}"
          ports:
            - containerPort: 9980
              name: http
              protocol: TCP
          resources:
            {{- toYaml .Values.collabora.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /hosting/discovery
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /hosting/discovery
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          securityContext:
            capabilities:
              add:
                - MKNOD
{{- end }}
