{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameCollabora" "appNameSuffix" "") -}}
{{- if and .Values.collabora.enabled .Values.gateway.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-collabora
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    oc-metrics: enabled
    {{- include "oc.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.httproute.gateway.name }}
      namespace: {{ .Values.gateway.httproute.gateway.namespace }}
      sectionName: oc-collabora-https
  hostnames:
    - {{ .Values.collabora.domain }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .appName }}
          port: 9980
{{- end }}
