{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameCollabora" "appNameSuffix" "") -}}
{{- if .Values.collabora.enabled }}
apiVersion: v1
kind: Service
{{ include "oc.metadata" . | nindent 0 }}
spec:
  type: ClusterIP
  ports:
    - port: 9980
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .appName }}
{{- end }}
