{{- if .Values.services.storageusers.persistence.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameStorageUsers" "appNameSuffix" "") -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: storage-users-clean-expired-uploads
  namespace: {{ template "oc.namespace" . }}
  labels:
    {{- include "oc.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.services.storageusers.maintenance.cleanUpExpiredUploads.schedule | quote }}
  {{- with .Values.services.storageusers.maintenance.cleanUpExpiredUploads.timezone }}
  timeZone: {{ . | quote }}
  {{- end }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.services.storageusers.maintenance.cleanUpExpiredUploads.startingDeadlineSeconds }}
  suspend: {{ not .Values.services.storageusers.maintenance.cleanUpExpiredUploads.enabled }}
  jobTemplate:
    spec:
      parallelism: 1
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: storage-users-clean-expired-uploads
            {{- include "oc.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          {{- include "oc.securityContextAndtopologySpreadConstraints" . | nindent 10 }}
          {{- include "oc.priorityClassName" $.jobPriorityClassName | nindent 10 }}
          {{- include "oc.hostAliases" $ | nindent 10 }}
          nodeSelector: {{ toYaml $.jobNodeSelector | nindent 12 }}
          containers:
            - name: storage-users-clean-expired-uploads
              {{- include "oc.jobContainerImageOC" . | nindent 14 }}
              command: ["opencloud"]
              args: ["storage-users", "uploads", "sessions", "--clean"]
              securityContext:
                runAsNonRoot: true
                runAsUser: {{ .Values.securityContext.runAsUser }}
                runAsGroup: {{ .Values.securityContext.runAsGroup }}
                readOnlyRootFilesystem: true
              env:
                {{- include "oc.serviceRegistry" . | nindent 16 }}
                # logging
                - name: STORAGE_USERS_LOG_COLOR
                  value: {{ .Values.logging.color | quote }}
                - name: STORAGE_USERS_LOG_LEVEL
                  value: {{ .Values.logging.level | quote }}
                - name: STORAGE_USERS_LOG_PRETTY
                  value: {{ .Values.logging.pretty | quote }}

                # OC storage driver (decomposed filesystem)
                {{- if  eq .Values.services.storageusers.storageBackend.driver "decomposed" }}
                - name: STORAGE_USERS_DRIVER
                  value: decomposed
                {{- end }}

                # DECOMPOSEDS3 storage driver (decomposed filesystem)
                {{- if  eq .Values.services.storageusers.storageBackend.driver "decomposeds3" }}
                - name: STORAGE_USERS_DRIVER
                  value: decomposeds3
                - name: STORAGE_USERS_DECOMPOSEDS3_ENDPOINT
                  value: {{ .Values.services.storageusers.storageBackend.driverConfig.decomposeds3.endpoint | default (printf "http://minio.%s.svc.cluster.local:9000" (include "oc.namespace" $)) | quote }}
                - name: STORAGE_USERS_DECOMPOSEDS3_REGION
                  value: {{ .Values.services.storageusers.storageBackend.driverConfig.decomposeds3.region | quote }}
                - name: STORAGE_USERS_DECOMPOSEDS3_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.s3CredentialsSecret" . }}
                      key: accessKey
                - name: STORAGE_USERS_DECOMPOSEDS3_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.s3CredentialsSecret" . }}
                      key: secretKey
                - name: STORAGE_USERS_DECOMPOSEDS3_BUCKET
                  value: {{ .Values.services.storageusers.storageBackend.driverConfig.decomposeds3.bucket | quote }}
                {{- end }}

                - name: STORAGE_USERS_JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.jwtSecret" . }}
                      key: jwt-secret

                - name: OC_TRANSFER_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.transferSecret" . }}
                      key: transfer-secret

                - name: STORAGE_USERS_MOUNT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "config.storageUsers" . }}
                      key: storage-uuid

                - name: STORAGE_USERS_SERVICE_ACCOUNT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "config.authService" . }}
                      key: service-account-id
                - name: STORAGE_USERS_SERVICE_ACCOUNT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.serviceAccountSecret" . }}
                      key: service-account-secret

                {{- include "oc.caEnv" $ | nindent 16}}

              resources: {{ toYaml .jobResources | nindent 16 }}

              volumeMounts:
                - name: tmp-volume
                  mountPath: /tmp
                - name: {{ include "oc.persistence.dataVolumeName" . }}
                  mountPath: /var/lib/opencloud
                {{- include "oc.caPath" $ | nindent 16}}

          {{- include "oc.imagePullSecrets" $ | nindent 10 }}
          volumes:
            - name: tmp-volume
              emptyDir: {}
            {{- include "oc.persistence.dataVolume" . | nindent 12 }}
            {{- include "oc.caVolume" $ | nindent 12}}
{{ end }}
{{- if .Values.services.storageusers.persistence.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameStorageUsers" "appNameSuffix" "") -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: storage-users-purge-expired-trash-bin-items
  namespace: {{ template "oc.namespace" . }}
  labels:
    {{- include "oc.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.services.storageusers.maintenance.purgeExpiredTrashBinItems.schedule | quote }}
  {{- with .Values.services.storageusers.maintenance.purgeExpiredTrashBinItems.timezone }}
  timeZone: {{ . | quote }}
  {{- end }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.services.storageusers.maintenance.purgeExpiredTrashBinItems.startingDeadlineSeconds }}
  suspend: {{ not .Values.services.storageusers.maintenance.purgeExpiredTrashBinItems.enabled }}
  jobTemplate:
    spec:
      parallelism: 1
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: storage-users-purge-expired-trash-bin-items
            {{- include "oc.labels" . | nindent 12 }}

        spec:
          restartPolicy: Never
          {{- include "oc.securityContextAndtopologySpreadConstraints" . | nindent 10 }}
          {{- include "oc.priorityClassName" $.jobPriorityClassName | nindent 10 }}
          {{- include "oc.hostAliases" $ | nindent 10 }}
          nodeSelector: {{ toYaml $.jobNodeSelector | nindent 12 }}
          containers:
            - name: storage-users-purge-expired-trash-bin-items
              {{- include "oc.jobContainerImageOC" . | nindent 14 }}
              command: ["opencloud"]
              args: ["storage-users", "trash-bin", "purge-expired"]
              securityContext:
                runAsNonRoot: true
                runAsUser: {{ .Values.securityContext.runAsUser }}
                runAsGroup: {{ .Values.securityContext.runAsGroup }}
                readOnlyRootFilesystem: true
              env:
                {{- include "oc.serviceRegistry" . | nindent 16 }}
                {{- include "oc.events" . | nindent 16 }}

                # logging
                - name: STORAGE_USERS_LOG_COLOR
                  value: {{ .Values.logging.color | quote }}
                - name: STORAGE_USERS_LOG_LEVEL
                  value: {{ .Values.logging.level | quote }}
                - name: STORAGE_USERS_LOG_PRETTY
                  value: {{ .Values.logging.pretty | quote }}

                - name: STORAGE_USERS_JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.jwtSecret" . }}
                      key: jwt-secret

                - name: OC_TRANSFER_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.transferSecret" . }}
                      key: transfer-secret

                - name: STORAGE_USERS_MOUNT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "config.storageUsers" . }}
                      key: storage-uuid

                - name: STORAGE_USERS_SERVICE_ACCOUNT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "config.authService" . }}
                      key: service-account-id
                - name: STORAGE_USERS_SERVICE_ACCOUNT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.serviceAccountSecret" . }}
                      key: service-account-secret

                {{- include "oc.caEnv" $ | nindent 16}}

              resources: {{ toYaml .jobResources | nindent 16 }}

              volumeMounts:
                - name: tmp-volume
                  mountPath: /tmp
                - name: {{ include "oc.persistence.dataVolumeName" . }}
                  mountPath: /var/lib/opencloud
                {{- include "oc.caPath" $ | nindent 16}}

          {{- include "oc.imagePullSecrets" $ | nindent 10 }}
          volumes:
            - name: tmp-volume
              emptyDir: {}
            {{- include "oc.persistence.dataVolume" . | nindent 12 }}
            {{- include "oc.caVolume" $ | nindent 12}}
{{ end }}

{{- if .Values.services.storageusers.persistence.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameStorageUsers" "appNameSuffix" "") -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: storage-users-restart-postprocessing
  namespace: {{ template "oc.namespace" . }}
  labels:
    {{- include "oc.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.services.storageusers.maintenance.restartPostprocessing.schedule | quote }}
  {{- with .Values.services.storageusers.maintenance.restartPostprocessing.timezone }}
  timeZone: {{ . | quote }}
  {{- end }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.services.storageusers.maintenance.restartPostprocessing.startingDeadlineSeconds }}
  suspend: {{ not .Values.services.storageusers.maintenance.restartPostprocessing.enabled }}
  jobTemplate:
    spec:
      parallelism: 1
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: storage-users-restart-postprocessing
            {{- include "oc.labels" . | nindent 12 }}

        spec:
          restartPolicy: Never
          {{- include "oc.securityContextAndtopologySpreadConstraints" . | nindent 10 }}
          {{- include "oc.priorityClassName" $.jobPriorityClassName | nindent 10 }}
          {{- include "oc.hostAliases" $ | nindent 10 }}
          nodeSelector: {{ toYaml $.jobNodeSelector | nindent 12 }}
          containers:
            - name: storage-users-restart-postprocessing
              {{- include "oc.jobContainerImageOC" . | nindent 14 }}
              command: ["opencloud"]
              args: ["storage-users", "uploads", "sessions", "--restart", "--processing=true"]
              securityContext:
                runAsNonRoot: true
                runAsUser: {{ .Values.securityContext.runAsUser }}
                runAsGroup: {{ .Values.securityContext.runAsGroup }}
                readOnlyRootFilesystem: true
              env:
                {{- include "oc.serviceRegistry" . | nindent 16 }}
                {{- include "oc.events" . | nindent 16 }}

                # logging
                - name: STORAGE_USERS_LOG_COLOR
                  value: {{ .Values.logging.color | quote }}
                - name: STORAGE_USERS_LOG_LEVEL
                  value: {{ .Values.logging.level | quote }}
                - name: STORAGE_USERS_LOG_PRETTY
                  value: {{ .Values.logging.pretty | quote }}

                - name: STORAGE_USERS_JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.jwtSecret" . }}
                      key: jwt-secret

                - name: OC_TRANSFER_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.transferSecret" . }}
                      key: transfer-secret

                - name: STORAGE_USERS_MOUNT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "config.storageUsers" . }}
                      key: storage-uuid

                - name: STORAGE_USERS_SERVICE_ACCOUNT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "config.authService" . }}
                      key: service-account-id
                - name: STORAGE_USERS_SERVICE_ACCOUNT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.serviceAccountSecret" . }}
                      key: service-account-secret

                {{- include "oc.caEnv" $ | nindent 16}}

              resources: {{ toYaml .jobResources | nindent 16 }}

              volumeMounts:
                - name: tmp-volume
                  mountPath: /tmp
                - name: {{ include "oc.persistence.dataVolumeName" . }}
                  mountPath: /var/lib/opencloud
                {{- include "oc.caPath" $ | nindent 16}}

          {{- include "oc.imagePullSecrets" $ | nindent 10 }}
          volumes:
            - name: tmp-volume
              emptyDir: {}
            {{- include "oc.caVolume" $ | nindent 12}}
            {{- include "oc.persistence.dataVolume" . | nindent 12 }}
{{ end }}
