{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameStorageSystem" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "oc.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "oc.affinity" $ | nindent 6 }}
      {{- include "oc.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- if and $.Values.services.storagesystem.persistence.enabled $.Values.services.storagesystem.persistence.chownInitContainer }}
      initContainers:
        - name: init-chown-data
          {{- include "oc.initContainerImage" $ | nindent 10 }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          {{- include "oc.initChownDataCommand" $ | nindent 10 }}
          volumeMounts:
          - name: {{ include "oc.persistence.dataVolumeName" . }}
            mountPath: /var/lib/opencloud
      {{ end }}
      {{- include "oc.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "oc.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "oc.image" $ | nindent 10 }}
          command: ["opencloud"]
          args: ["storage-system", "server"]
          {{- include "oc.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "oc.serviceRegistry" . | nindent 12 }}
            {{- include "oc.cacheStore" . | nindent 12 }}

            # logging
            - name: STORAGE_SYSTEM_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: STORAGE_SYSTEM_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: STORAGE_SYSTEM_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: STORAGE_SYSTEM_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: STORAGE_SYSTEM_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: STORAGE_SYSTEM_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: STORAGE_SYSTEM_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: STORAGE_SYSTEM_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            # bind configuration
            - name: STORAGE_SYSTEM_GRPC_ADDR
              value: 0.0.0.0:9215
            - name: STORAGE_SYSTEM_DEBUG_ADDR
              value: 0.0.0.0:9217

            # external availability data gateway
            - name: STORAGE_SYSTEM_HTTP_ADDR
              value: 0.0.0.0:9216
            - name: STORAGE_SYSTEM_DATA_SERVER_URL
              value: http://{{ .appName }}:9216/data

            - name: STORAGE_SYSTEM_DRIVER
              value: decomposed

            - name: STORAGE_SYSTEM_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.storageSystemJWTSecret" . }}
                  key: storage-system-jwt-secret

            - name: OC_SYSTEM_USER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.storageSystemSecret" . }}
                  key: api-key

            - name: OC_SYSTEM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.storageSystemSecret" . }}
                  key: user-id

            {{- include "oc.caEnv" $ | nindent 12}}

          {{- include "oc.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: grpc
              containerPort: 9215
            - name: http
              containerPort: 9216
            - name: metrics-debug
              containerPort: 9217

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: {{ include "oc.persistence.dataVolumeName" . }}
              mountPath: /var/lib/opencloud
            {{- include "oc.caPath" $ | nindent 12}}

      {{- include "oc.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        {{- include "oc.caVolume" $ | nindent 8}}
        {{- include "oc.persistence.dataVolume" . | nindent 8 }}
