apiVersion: v2
name: opencloud-full
description: openCloud Helm chart
keywords:
  - opencloud
  - oc
maintainers:
  - name: OpenCloud EU
    email: info@opencloud.eu
    url: https://opencloud.eu
type: application
version: 3.0.0
# renovate: datasource=docker depName=opencloudeu/opencloud-rolling
appVersion: 3.0.0
kubeVersion: ""
sources:
  - https://github.com/opencloud-eu/helm
  - https://github.com/opencloud-eu/opencloud
  - https://github.com/cs3org/reva