{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameOnlyOffice" "appNameSuffix" "") -}}
{{- if .Values.onlyoffice.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .appName }}-config
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    oc-metrics: enabled
    {{- include "oc.labels" . | nindent 4 }}
data:
  entrypoint-override.sh: |
    #!/bin/sh
    set -e

    # Create a writable directory for the configuration
    mkdir -p /tmp/onlyoffice/documentserver

  
    exec /app/ds/run-document-server.sh

  local.json: |-
    {
      "services": {
        "CoAuthoring": {
          "token": {
            "enable": {
              "request": {
                "inbox": true,
                "outbox": true
              },
              "browser": true
            },
            "inbox": {
              "header": "Authorization"
            },
            "outbox": {
              "header": "Authorization"
            }
          },
          "secret": {
            "inbox": {
              "string": "{{ .Values.onlyoffice.config.coAuthoring.secret.inbox | default "B8LjkNqGxn6gf8bkuBUiMwyuCFwFddnu" }}"
            },
            "outbox": {
              "string": "{{ .Values.onlyoffice.config.coAuthoring.secret.outbox | default "B8LjkNqGxn6gf8bkuBUiMwyuCFwFddnu" }}"
            },
            "session": {
              "string": "{{ .Values.onlyoffice.config.coAuthoring.secret.session | default "B8LjkNqGxn6gf8bkuBUiMwyuCFwFddnu" }}"
            }
          }
        }
      },
      "rabbitmq": {
        "url": "{{ .Values.onlyoffice.config.rabbitmq.url | default "amqp://guest:guest@localhost" }}"
      },
      "FileConverter": {
        "converter": {
          "inputLimits": [
            {
              "type": "docx;dotx;docm;dotm",
              "zip": {
                "uncompressed": "1GB",
                "template": "*.xml"
              }
            },
            {
              "type": "xlsx;xltx;xlsm;xltm",
              "zip": {
                "uncompressed": "1GB",
                "template": "*.xml"
              }
            },
            {
              "type": "pptx;ppsx;potx;pptm;ppsm;potm",
              "zip": {
                "uncompressed": "1GB",
                "template": "*.xml"
              }
            }
          ]
        }
      }
    }
{{- end }}
