{{ if .Values.features.appsIntegration.enabled }}
{{- range $officeSuite := .Values.features.appsIntegration.wopiIntegration.officeSuites }}
{{ if $officeSuite.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" $ "appName" "appNameCollaboration" "appNameSuffix" (regexReplaceAll "\\W+" (lower $officeSuite.name) "-")) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.appName }}
  namespace: {{ template "oc.namespace" $ }}
  labels:
    app: {{ $.appName }}
    oc-metrics: enabled
    {{- include "oc.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{ $.appName }}
  ports:
    - name: grpc
      port: 9301
      protocol: TCP
      appProtocol: {{ $.Values.service.appProtocol.grpc | quote}}
    - name: http
      port: 9300
      protocol: TCP
      appProtocol: {{ $.Values.service.appProtocol.http | quote}}
    - name: metrics-debug
      port: 9304
      protocol: TCP
      appProtocol: {{ $.Values.service.appProtocol.http | quote}}
{{ end }}
{{ end }}
{{ end }}
