{{- if or (not .Values.secretRefs.machineAuthApiKeySecretRef) }}
{{- $params := (dict)}}
{{- $_ := set $params "machine-auth-api-key" (randAlphaNum 30) }}
{{- include "oc.secret" (dict "scope" . "name" "machine-auth-api-key" "params" $params)}}
{{- end }}
