
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameStorageShares" "appNameSuffix" "") -}}
{{- $_ := set . "autoscaling" (default (default (dict) .Values.autoscaling) .Values.services.storageshares.autoscaling) -}}
{{ include "oc.hpa" . }}
