{{- if and .Values.onlyoffice.collaboration.enabled .Values.onlyoffice.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencloud.fullname" . }}-collaboration
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: collaboration
  annotations:
    helm.sh/hook-weight: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "opencloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: collaboration
  template:
    metadata:
      labels:
        {{- include "opencloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: collaboration
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        # Wait for OpenCloud to be ready
        - name: wait-for-opencloud
          image: busybox
          command: ['sh', '-c', 'until wget -q -O- http://{{ include "opencloud.opencloud.fullname" . }}:9200/health; do echo waiting for opencloud; sleep 5; done;']         
        # Wait for OnlyOffice to be ready
        - name: wait-for-onlyoffice
          image: busybox
          command: ['sh', '-c', 'until wget -q -O- http://{{ include "opencloud.fullname" . }}-onlyoffice:80/hosting/discovery; do echo waiting for onlyoffice; sleep 2; done;']
      containers:
        - name: collaboration
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "opencloud collaboration server"]
          env:
            - name: COLLABORATION_GRPC_ADDR
              value: "0.0.0.0:9301"
            - name: COLLABORATION_HTTP_ADDR
              value: "0.0.0.0:9300"
            - name: MICRO_REGISTRY
              value: "nats-js-kv"
            - name: MICRO_REGISTRY_ADDRESS
              value: "{{ include "opencloud.opencloud.fullname" . }}.{{ include "opencloud.namespace" . }}.svc.cluster.local:9233"
            - name: COLLABORATION_WOPI_SRC
              value: "https://{{ include "opencloud.wopi.domain" . }}"
            - name: COLLABORATION_APP_NAME
              value: "OnlyOffice"
            - name: COLLABORATION_APP_PRODUCT
              value: "OnlyOffice"
            - name: COLLABORATION_APP_ADDR
              value: "https://{{ include "opencloud.onlyoffice.domain" . }}"
            - name: COLLABORATION_APP_ICON
              value: "https://{{ include "opencloud.onlyoffice.domain" . }}/web-apps/apps/documenteditor/main/resources/img/favicon.ico"
            - name: COLLABORATION_APP_PROOF_DISABLE
              value: "true"
            - name: COLLABORATION_APP_INSECURE
              value: "{{ .Values.opencloud.insecure }}"
            - name: COLLABORATION_CS3API_DATAGATEWAY_INSECURE
              value: "{{ .Values.opencloud.insecure }}"
            - name: COLLABORATION_LOG_LEVEL
              value: "{{ .Values.opencloud.logLevel }}"
            - name: OC_URL
              value: "https://{{ include "opencloud.domain" . }}"
            - name: OC_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencloud.fullname" . }}-oc-secrets
                  key: jwt-secret
            - name: COLLABORATION_WOPI_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencloud.fullname" . }}-oc-secrets
                  key: wopi-secret
          ports:
            - name: http
              containerPort: 9300
              protocol: TCP
            - name: grpc
              containerPort: 9301
              protocol: TCP
          volumeMounts:
            - name: etc-opencloud
              mountPath: /etc/opencloud
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl --silent --fail http://opencloud-opencloud:9200/app/list | grep '"name":"OnlyOffice"'
            timeoutSeconds: 10
            initialDelaySeconds: 200
            periodSeconds: 5
            failureThreshold: 1
          resources:
            {{- toYaml .Values.onlyoffice.collaboration.resources | nindent 12 }}
      volumes:
        - name: etc-opencloud
          # Use emptyDir instead of mounting the PVC to avoid conflicts
          emptyDir: {}
{{- end }}
