{{ if .Values.features.ocm.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameOcm" "appNameSuffix" "") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    oc-metrics: enabled
    {{- include "oc.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .appName }}
  ports:
    - name: grpc
      port: 9282
      protocol: TCP
      appProtocol: {{ $.Values.service.appProtocol.grpc | quote}}
    - name: http
      port: 9280
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol.http | quote }}
    - name: metrics-debug
      port: 9281
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol.http | quote }}
{{ end }}
