{{ if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oc-metrics
  namespace: {{ template "oc.namespace" . }}
spec:
  selector:
    matchLabels:
      oc-metrics: enabled
  endpoints:
    - port: metrics-debug
      interval: {{ .Values.monitoring.interval | quote }}
      scrapeTimeout: {{  .Values.monitoring.scrapeTimeout | quote }}
      path: /metrics
{{ end }}
