{{- if .Values.ldap.internal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencloud.openldap.fullname" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: openldap
spec:
  type: ClusterIP
  ports:
    - port: 1389
      targetPort: ldap
      protocol: TCP
      name: ldap
    - port: 1636
      targetPort: ldaps
      protocol: TCP
      name: ldaps
  selector:
    {{- include "opencloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: openldap
{{- end }}
