{{- if not .Values.features.externalUserManagement.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameIdp" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . }}
  annotations:
    ignore-check.kube-linter.io/env-var-secret: "IDP_ENCRYPTION_SECRET_FILE is no secret, it's the file path to the secret"
spec:
  {{- include "oc.selector" . | nindent 2 }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "oc.affinity" $ | nindent 6 }}
      {{- include "oc.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "oc.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "oc.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "oc.image" $ | nindent 10 }}
          command: ["opencloud"]
          args: ["idp", "server"]
          {{- include "oc.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "oc.serviceRegistry" . | nindent 12 }}

            - name: IDP_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: IDP_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: IDP_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: IDP_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: IDP_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: IDP_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: IDP_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: IDP_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: IDP_HTTP_ADDR
              value: 0.0.0.0:9130
            - name: IDP_DEBUG_ADDR
              value: 0.0.0.0:9134

            - name: OC_URL
              value: "https://{{ .Values.externalDomain }}"

            - name: IDP_LDAP_URI
              value: ldaps://{{ .appNameIdm }}:9235

            - name: IDP_LDAP_TLS_CACERT
              value: /etc/opencloud/ldap-ca/ldap-ca.crt

            - name: IDP_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.ldapBindSecret" . }}
                  key: idp-ldap-bind-password

            - name: IDP_SIGNING_PRIVATE_KEY_FILES
              value: /etc/opencloud/idp/private-key.pem

            - name: IDP_ENCRYPTION_SECRET_FILE
              value: /etc/opencloud/idp/encryption.key

            {{- include "oc.caEnv" $ | nindent 12}}

          {{- include "oc.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: http
              containerPort: 9130
            - name: metrics-debug
              containerPort: 9134

          volumeMounts:
            - name: oc-data-tmp
              mountPath: /var/lib/opencloud # we mount that volume to apply fsGroup to that path, so that the idp can write the temporary idp/tmp/identifier-registration.yaml file
            - name: ldap-ca
              mountPath: /etc/opencloud/ldap-ca
              readOnly: true
            - name: idp-secrets
              mountPath: /etc/opencloud/idp
              readOnly: true
            {{- include "oc.caPath" $ | nindent 12}}

      {{- include "oc.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: oc-data-tmp
          emptyDir: {}
        - name: ldap-ca
          secret:
            secretName: {{ include "secrets.ldapCASecret" . }}
        - name: idp-secrets
          secret:
            secretName: {{ include "secrets.idpSecret" . }}
        {{- include "oc.caVolume" $ | nindent 8}}
{{- end }}
