{{- if .Values.features.roles.customRoles }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameSettings" "appNameSuffix" "") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .appName }}-role-config
  namespace: {{ template "oc.namespace" . }}
  labels:
    {{- include "oc.labels" . | nindent 4 }}
data:
  custom-roles.json: {{ .Values.features.roles.customRoles | quote }}
{{- end }}
