{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameSettings" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "oc.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" true) | nindent 4 }}
    spec:
      {{- include "oc.affinity" $ | nindent 6 }}
      {{- include "oc.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "oc.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "oc.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "oc.image" $ | nindent 10 }}
          command: ["opencloud"]
          args: ["settings", "server"]
          {{- include "oc.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "oc.serviceRegistry" . | nindent 12 }}
            {{- include "oc.cors" . |nindent 12 }}
            {{- include "oc.cacheStore" . | nindent 12 }}

            - name: OC_DEFAULT_LANGUAGE
              value: {{ default "en" .Values.features.language.default | quote }}

            - name: SETTINGS_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: SETTINGS_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: SETTINGS_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: SETTINGS_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: SETTINGS_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: SETTINGS_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: SETTINGS_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: SETTINGS_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: SETTINGS_HTTP_ADDR
              value: 0.0.0.0:9190
            - name: SETTINGS_GRPC_ADDR
              value: 0.0.0.0:9191
            - name: SETTINGS_DEBUG_ADDR
              value: 0.0.0.0:9194

            {{- if not .Values.features.externalUserManagement.oidc.roleAssignment.enabled }}
            - name: SETTINGS_ADMIN_USER_ID
            {{- if .Values.features.externalUserManagement.enabled }}
              value: {{ .Values.features.externalUserManagement.adminUUID | quote }}
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.adminUser" . }}
                  key: user-id
            {{- end }}
            {{- end }}

            {{- if or .Values.features.roles.customRoles .Values.features.roles.customRolesConfigRef }}
            - name: SETTINGS_BUNDLES_PATH
              value: /etc/opencloud/custom-roles.json
            {{- end }}
            - name: SETTINGS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.jwtSecret" . }}
                  key: jwt-secret

            - name: SETTINGS_SERVICE_ACCOUNT_IDS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "config.authService" . }}
                  key: service-account-id

            - name: OC_SYSTEM_USER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.storageSystemSecret" . }}
                  key: api-key
            - name: OC_SYSTEM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.storageSystemSecret" . }}
                  key: user-id

            {{- include "oc.caEnv" $ | nindent 12}}

          {{- include "oc.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9190
            - name: grpc
              containerPort: 9191
            - name: metrics-debug
              containerPort: 9194

          volumeMounts:
          {{- if or .Values.features.roles.customRoles .Values.features.roles.customRolesConfigRef }}
            - name: oc-role-config
              mountPath: /etc/opencloud
          {{- end }}
            {{- include "oc.caPath" $ | nindent 12}}

      {{- include "oc.imagePullSecrets" $ | nindent 6 }}

      volumes:
      {{- if .Values.features.roles.customRoles }}
        - name: oc-role-config
          configMap:
            name: {{ .appName }}-role-config
      {{- end }}
      {{- if .Values.features.roles.customRolesConfigRef }}
        - name: oc-role-config
          configMap:
            name: {{ .Values.features.roles.customRolesConfigRef }}
      {{- end }}
        {{- include "oc.caVolume" $ | nindent 8}}
