{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameMinio" "appNameSuffix" "") -}}
{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  replicas: 1
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-minio-bucket
          image: "{{ .Values.initContainerImage.repository }}:{{ .Values.initContainerImage.tag }}"
          imagePullPolicy: {{ .Values.initContainerImage.pullPolicy | default "IfNotPresent" }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          command: ['sh', '-c', 'mkdir -p /data/opencloud-bucket']
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: minio
          image: "{{ .Values.minio.image.registry }}/{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag | default .Values.minio.version }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy | default "IfNotPresent" }}
          args:
            - server
            - --console-address
            - :9001
            - /data
          env:
            - name: MINIO_ROOT_USER
              value: {{.Values.minio.config.rootUser }}
            - name: MINIO_ROOT_PASSWORD
              value: {{.Values.minio.config.rootPassword }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.minio.config.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .appName }}
{{- end }}
