{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameMinio" "appNameSuffix" "") -}}
{{- if .Values.minio.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .appName }}
  namespace: {{ template "oc.namespace" . }}
  annotations:
    helm.sh/resource-policy: "keep"
  labels:
    app: {{ .appName }}
    oc-metrics: enabled
    {{- include "oc.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.config.persistence.size }}
{{- end }}
