{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameProxy" "appNameSuffix" "") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    oc-metrics: enabled
    {{- include "oc.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .appName }}
  ports:
    - name: http
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol.http | quote}}
      port: 9200
    - name: metrics-debug
      port: 9205
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol.http | quote}}
