{{- if not .Values.features.externalUserManagement.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameIdm" "appNameSuffix" "") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    oc-metrics: enabled
    {{- include "oc.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .appName }}
  ports:
    - name: ldaps
      port: 9235
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol.ldaps | quote}}
    - name: metrics-debug
      port: 9239
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol.http | quote}}
{{- end }}
