{{- if .Values.features.emailNotifications.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameNotifications" "appNameSuffix" "") -}}
{{- $_ := set . "autoscaling" (default (default (dict) .Values.autoscaling) .Values.services.notifications.autoscaling) -}}
{{ include "oc.hpa" . }}
{{- end }}
