{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameKeycloak" "appNameSuffix" "") -}}
{{- if .Values.keycloak.enabled  }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-keycloak
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    oc-metrics: enabled
    {{- include "oc.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.httproute.gateway.name }}
      namespace: {{ .Values.gateway.httproute.gateway.namespace }}
      sectionName: oc-keycloak-https
  hostnames:
    - {{ .Values.keycloak.domain }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .appName }}
          port: 80
{{- end }}
