apiVersion: v1
kind: Secret
metadata:
  name: ldap-bind-secrets
  namespace: opencloud
stringData:
  reva-ldap-bind-password: admin
---          
apiVersion: v1
kind: Secret
metadata:
  name: s3secret
  namespace: opencloud
stringData:
  accessKey: opencloud
  secretKey: opencloud-secret-key
