{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameTika" "appNameSuffix" "") -}}
{{- if .Values.tika.enabled }}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "oc.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      securityContext:
        fsGroup: {{ .Values.tika.securityContext.fsGroup | default 1000 }}
        runAsUser: {{ .Values.tika.securityContext.runAsUser | default 1000 }}
        runAsGroup: {{ .Values.tika.securityContext.runAsGroup | default 1000 }}
        runAsNonRoot: {{ .Values.tika.securityContext.runAsNonRoot | default true }}
      containers:
        - name: tika
          image: "{{ .Values.tika.image.registry }}/{{ .Values.tika.image.repository }}:{{ .Values.tika.image.tag }}"
          imagePullPolicy: {{ .Values.tika.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 9998
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /tika # Tika's version endpoint, can be used as a health check
              port: http
            initialDelaySeconds: {{ .Values.tika.probes.liveness.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.tika.probes.liveness.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.tika.probes.liveness.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.tika.probes.liveness.failureThreshold | default 3 }}
            successThreshold: {{ .Values.tika.probes.liveness.successThreshold | default 1 }}
          readinessProbe:
            httpGet:
              path: /tika # Tika's version endpoint, can be used as a health check
              port: http
            initialDelaySeconds: {{ .Values.tika.probes.readiness.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.tika.probes.readiness.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.tika.probes.readiness.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.tika.probes.readiness.failureThreshold | default 3 }}
            successThreshold: {{ .Values.tika.probes.readiness.successThreshold | default 1 }}
          resources:
            {{- toYaml .Values.tika.resources | nindent 12 }}
{{- end }}
