{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameTika" "appNameSuffix" "") -}}
{{- if .Values.tika.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    oc-metrics: enabled
    {{- include "oc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.tika.service.port | default 9000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .appName }}
{{- end }}
