{{- if and .Values.onlyoffice.collaboration.enabled .Values.onlyoffice.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.fullname" . }}-oc-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: collaboration
data:
  # Generate a random JWT secret if not provided
  jwt-secret: {{ .Values.opencloud.jwtSecret | default (randAlphaNum 32) | b64enc }}
  # Generate a random WOPI secret if not provided
  wopi-secret: {{ .Values.opencloud.wopiSecret | default (randAlphaNum 32) | b64enc }}
{{- end }}
