apiVersion: v1
kind: Namespace
metadata:
  name: opencloud
---
apiVersion: v1
kind: Namespace
metadata:
  name: openldap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opencloud-config
  namespace: opencloud
data:
  ###############################################################################
  # Global Configuration
  ###############################################################################
  EXTERNAL_DOMAIN: "cloud.opencloud.test"
  OPENCLOUD_WEB_URL: "https://www.opencloud.eu"
  OPENCLOUD_LOGGING_LEVEL: "debug"
  INGRESS_ENABLED: "false"
  INGRESS_CLASS_NAME: "nginx"
  INGRESS_PROXY_BODY_SIZE: "1024m"
  GATEWAY_HTTPROUTE_ENABLED: "true"
  APPS_INTEGRATION_ENABLED: "true"
  WEB_OIDC_WEB_CLIENT_ID: "web"
  IDM_PERSISTENCE_ENABLED: "false"
  IDM_PERSISTENCE_SIZE: "10Gi"
  NATS_PERSISTENCE_ENABLED: "true"
  NATS_PERSISTENCE_SIZE: "10Gi"
  OCM_PERSISTENCE_ENABLED: "false"
  OCM_PERSISTENCE_SIZE: "1Gi"
  ONLYOFFICE_PERSISTENCE_SIZE: "2Gi"
  SEARCH_EXTRACTOR_TYPE: "tika"
  SEARCH_PERSISTENCE_ENABLED: "true"
  SEARCH_PERSISTENCE_SIZE: "10Gi"
  STORAGE_USERS_BACKEND_DRIVER: "decomposeds3"
  STORAGE_SYSTEM_PERSISTENCE_ENABLED: "true"
  STORAGE_SYSTEM_PERSISTENCE_SIZE: "5Gi"
  STORAGE_USERS_PERSISTENCE_ENABLED: "true"
  STORAGE_USERS_PERSISTENCE_SIZE: "50Gi"
  THUMBNAILS_PERSISTENCE_ENABLED: "true"
  THUMBNAILS_PERSISTENCE_SIZE: "10Gi"
  WEB_PERSISTENCE_ENABLED: "true"
  WEB_PERSISTENCE_SIZE: "1Gi"

  OIDC_IDP_INSECURE: "true"
  OC_HTTP_API_INSECURE: "true"

  ###############################################################################
  # Internal Keycloak (for testing only)
  ###############################################################################
  KEYCLOAK_DOMAIN: "keycloak.opencloud.test"
  KEYCLOAK_ENABLED: "true"

  ###############################################################################
  # Internal Minio (for testing only)
  ###############################################################################
  MINIO_DOMAIN: "minio.opencloud.test"
  MINIO_ENABLED: "true"
  MINIO_PERSISTENCE_SIZE: "40Gi"

  ###############################################################################
  # LDAP Configuration
  ###############################################################################
  LDAP_URI: "ldaps://openldap.openldap.svc.cluster.local:636"
  LDAP_GLOBAL_DOMAIN: "opencloud.eu"
  LDAP_WRITEABLE: "true"
  LDAP_INSECURE: "true"
  LDAP_BIND_DN: "cn=admin,dc=opencloud,dc=eu"
  LDAP_USER_NAME_MATCH: "none"
  LDAP_USER_SCHEMA_ID: "openCloudUUID"
  LDAP_GROUP_SCHEMA_ID: "openCloudUUID"
  OPENLDAP_LTB_PASSWD_ENABLED: "false"
  OPENLDAP_REPLICATION_ENABLED: "false"
  OPENLDAP_REPLICA_COUNT: "1"

  ###############################################################################
  # OIDC Configuration
  ###############################################################################
  OIDC_ISSUER_URI: "https://keycloak.opencloud.test/realms/openCloud"
  EXTERNAL_USER_MANAGEMENT_ENABLED: "true"
  EXTERNAL_USER_MANAGEMENT_ADMIN_UUID: "0ab77e6d-23b4-4ba3-9843-a3b3efdcfc53"
  AUTOPROVISION_ACCOUNTS_ENABLED: "true"
  AUTOPROVISION_ACCOUNTS_CLAIM_USER_NAME: "sub"
  OIDC_USER_ID_CLAIM: "sub"
  OIDC_USER_ID_CLAIM_ATTRIBUTE_MAPPING: "username"
  OIDC_ROLE_ASSIGNMENT_CLAIM: "roles"

  ###############################################################################
  # Collabora Configuration
  ###############################################################################
  COLLABORA_URI: "https://collabora.opencloud.test"
  COLLABORA_DOMAIN: "collabora.opencloud.test"
  COLLABORA_ICON_URI: "https://collabora.opencloud.test/favicon.ico"
  COLLABORA_ENABLED: "true"
  COLLABORA_INSECURE: "true"
  COLLABORA_DISABLE_PROOF: "false"
  COLLABORA_INGRESS_ENABLED: "false"
  COLLABORA_INGRESS_CLASS_NAME: "nginx"
  COLLABORA_INGRESS_PROXY_BODY_SIZE: "1024m"

  ###############################################################################
  # OnlyOffice Configuration
  ###############################################################################
  ONLYOFFICE_URI: "https://onlyoffice.opencloud.test"
  ONLYOFFICE_DOMAIN: "onlyoffice.opencloud.test"
  ONLYOFFICE_ICON_URI: "https://onlyoffice.opencloud.test/web-apps/apps/documenteditor/main/resources/img/favicon.ico"
  ONLYOFFICE_ENABLED: "false"
  ONLYOFFICE_INSECURE: "true"
  ONLYOFFICE_DISABLE_PROOF: "false"
  ONLYOFFICE_INGRESS_ENABLED: "false"

  ###############################################################################
  # WOPI Configuration
  ###############################################################################
  WOPI_INGRESS_DOMAIN: "wopi.opencloud.test"
  WOPI_COLLABORA_TLS_HOST: "wopi-collabora.kube.opencloud.test"
