apiVersion: v1
kind: Namespace
metadata:
  name: opencloud
---
apiVersion: v1
kind: Namespace
metadata:
  name: openldap
---
apiVersion: v1
kind: Namespace
metadata:
  name: clamav
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opencloud-config
  namespace: opencloud
data:
  ###############################################################################
  # Global Configuration
  ###############################################################################
  EXTERNAL_DOMAIN: "cloud.opencloud.test"
  TAG: "3.0.0"

  ###############################################################################
  # Deployment Strategy
  ###############################################################################
  DEPLOY_TYPE: "Recreate"
  MAX_SURGE: "25%"
  MAX_UNAV: "25%"

  OPENCLOUD_WEB_URL: "https://www.opencloud.eu"
  OPENCLOUD_LOGGING_LEVEL: "debug"

  ###############################################################################
  # Ingress
  ###############################################################################
  INGRESS_ENABLED: "false"
  INGRESS_CLASS_NAME: "nginx"
  INGRESS_PROXY_BODY_SIZE: "1024m"
  GATEWAY_HTTPROUTE_ENABLED: "true"

  ###############################################################################
  # OIDC Configuration
  ###############################################################################
  OIDC_IDP_INSECURE: "true"
  OC_HTTP_API_INSECURE: "true"
  APPS_INTEGRATION_ENABLED: "true"
  WEB_OIDC_WEB_CLIENT_ID: "web"

  ###############################################################################
  # Persistence StorageClass and AccessModes (global defaults)
  ###############################################################################
  PERSISTENCE_STORAGE_CLASS_NAME: ""
  # Comma-separated for runtime to split into a list, e.g. "ReadWriteMany" or "ReadWriteOnce,ReadOnlyMany"
  PERSISTENCE_ACCESS_MODES: "ReadWriteOnce"

  ###############################################################################
  # Persistence (service PVC sizes and toggles)
  ###############################################################################
  IDM_PERSISTENCE_ENABLED: "false"
  IDM_PERSISTENCE_SIZE: "10Gi"
  NATS_PERSISTENCE_ENABLED: "true"
  NATS_PERSISTENCE_SIZE: "10Gi"
  OCM_PERSISTENCE_ENABLED: "false"
  OCM_PERSISTENCE_SIZE: "1Gi"
  ONLYOFFICE_PERSISTENCE_SIZE: "2Gi"
  SEARCH_PERSISTENCE_ENABLED: "true"
  SEARCH_PERSISTENCE_SIZE: "10Gi"
  STORAGE_USERS_BACKEND_DRIVER: "posix"
  STORAGE_SYSTEM_PERSISTENCE_ENABLED: "true"
  STORAGE_SYSTEM_PERSISTENCE_SIZE: "5Gi"
  STORAGE_USERS_PERSISTENCE_ENABLED: "true"
  STORAGE_USERS_PERSISTENCE_SIZE: "50Gi"
  THUMBNAILS_PERSISTENCE_ENABLED: "true"
  THUMBNAILS_PERSISTENCE_SIZE: "10Gi"
  WEB_PERSISTENCE_ENABLED: "true"
  WEB_PERSISTENCE_SIZE: "1Gi"

  # NATS specific persistence options
  # When true, a root init container will chown the NATS data volume before the main container starts.
  NATS_PERSISTENCE_CHOWN_INIT_CONTAINER: "false"

  ###############################################################################
  # Internal Keycloak (for testing only)
  ###############################################################################
  KEYCLOAK_DOMAIN: "keycloak.opencloud.test"
  KEYCLOAK_ENABLED: "true"

  ###############################################################################
  # Internal Minio (for testing only)
  ###############################################################################
  MINIO_DOMAIN: "minio.opencloud.test"
  MINIO_ENABLED: "false"
  MINIO_PERSISTENCE_SIZE: "40Gi"

  ###############################################################################
  # LDAP Configuration
  ###############################################################################
  LDAP_URI: "ldaps://openldap.openldap.svc.cluster.local:636"
  LDAP_GLOBAL_DOMAIN: "opencloud.eu"
  LDAP_WRITEABLE: "true"
  LDAP_INSECURE: "true"
  LDAP_BIND_DN: "cn=admin,dc=opencloud,dc=eu"
  LDAP_USER_NAME_MATCH: "none"
  LDAP_USER_SCHEMA_ID: "openCloudUUID"
  LDAP_GROUP_SCHEMA_ID: "openCloudUUID"
  OPENLDAP_LTB_PASSWD_ENABLED: "false"
  OPENLDAP_REPLICATION_ENABLED: "false"
  OPENLDAP_REPLICA_COUNT: "1"

  ###############################################################################
  # OIDC Configuration
  ###############################################################################
  OIDC_ISSUER_URI: "https://keycloak.opencloud.test/realms/openCloud"
  EXTERNAL_USER_MANAGEMENT_ENABLED: "true"
  EXTERNAL_USER_MANAGEMENT_ADMIN_UUID: "0ab77e6d-23b4-4ba3-9843-a3b3efdcfc53"
  AUTOPROVISION_ACCOUNTS_ENABLED: "true"
  AUTOPROVISION_ACCOUNTS_CLAIM_USER_NAME: "sub"
  OIDC_USER_ID_CLAIM: "sub"
  OIDC_USER_ID_CLAIM_ATTRIBUTE_MAPPING: "username"
  OIDC_ROLE_ASSIGNMENT_CLAIM: "roles"

  ###############################################################################
  # Search Configuration
  ###############################################################################
  SEARCH_EXTRACTOR_TYPE: "tika"

  ###############################################################################
  # Demo Users
  ###############################################################################
  DEMO_USERS_ENABLED: "false"

  ###############################################################################
  # Antivirus
  ###############################################################################
  ANTIVIRUS_ENABLED: "true"
  ANTIVIRUS_INFECTED_FILE_HANDLING: "delete"
  ANTIVIRUS_ICAP_URL: ""
  ANTIVIRUS_ICAP_SERVICE: ""

  ###############################################################################
  # Collabora Configuration
  ###############################################################################
  COLLABORA_URI: "https://collabora.opencloud.test"
  COLLABORA_DOMAIN: "collabora.opencloud.test"
  COLLABORA_ICON_URI: "https://collabora.opencloud.test/favicon.ico"
  COLLABORA_ENABLED: "true"
  COLLABORA_INSECURE: "true"
  COLLABORA_DISABLE_PROOF: "false"
  COLLABORA_INGRESS_ENABLED: "false"
  COLLABORA_INGRESS_CLASS_NAME: "nginx"
  COLLABORA_INGRESS_PROXY_BODY_SIZE: "1024m"

  ###############################################################################
  # OnlyOffice Configuration
  ###############################################################################
  ONLYOFFICE_URI: "https://onlyoffice.opencloud.test"
  ONLYOFFICE_DOMAIN: "onlyoffice.opencloud.test"
  ONLYOFFICE_ICON_URI: "https://onlyoffice.opencloud.test/web-apps/apps/documenteditor/main/resources/img/favicon.ico"
  ONLYOFFICE_ENABLED: "false"
  ONLYOFFICE_INSECURE: "true"
  ONLYOFFICE_DISABLE_PROOF: "false"
  ONLYOFFICE_INGRESS_ENABLED: "false"

  ###############################################################################
  # WOPI Configuration
  ###############################################################################
  WOPI_INGRESS_DOMAIN: "wopi.opencloud.test"
  WOPI_COLLABORA_TLS_HOST: "wopi-collabora.kube.opencloud.test"

  ###############################################################################
  # ClamAV Configuration
  ###############################################################################
  CLAMAV_REPLICA_COUNT: "1"
  CLAMAV_RESOURCES_LIMITS_CPU: "500m"
  CLAMAV_RESOURCES_LIMITS_MEMORY: "512Mi"
  CLAMAV_RESOURCES_REQUESTS_CPU: "250m"
  CLAMAV_RESOURCES_REQUESTS_MEMORY: "256Mi"
  CLAMAV_PERSISTENCE_SIZE: "10Gi"
  CLAMAV_FRESHCLAM_READONLY_ROOT_FILESYSTEM: "false"
  CLAMAV_FRESHCLAM_IMAGE_TAG: "1.4.0"
  CLAMAV_CLAMD_IMAGE_TAG: "1.4.0"
  CLAMAV_ICAP_IMAGE_TAG: "0.5.10"
  CLAMAV_ICAP_CLAMD_HOST: "opendesk-clamav-clamd"
  CLAMAV_MILTER_CLAMD_HOST: "opendesk-clamav-clamd"
