# Service account opencloud namespace
# 1) ServiceAccount — Flux will impersonate this
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: opencloud        # <- target namespace
---
# 2) Role — full power *inside* that namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-full-access
  namespace: opencloud
rules:
  - apiGroups:   ["*"]     # core & all groups
    resources:   ["*"]     # every namespaced resource
    verbs:       ["*"]     # get, list, create, delete, …
---
# 3) RoleBinding — ties the Role to the SA
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-full-access-binding
  namespace: opencloud
subjects:
  - kind:      ServiceAccount
    name:      flux
    namespace: opencloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:     Role
  name:     flux-full-access
---
# Service account openldap namespace
# 1) ServiceAccount — Flux will impersonate this
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: openldap        # <- target namespace
---
# 2) Role — full power *inside* that namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-full-access
  namespace: openldap
rules:
  - apiGroups:   ["*"]     # core & all groups
    resources:   ["*"]     # every namespaced resource
    verbs:       ["*"]     # get, list, create, delete, …
---
# 3) RoleBinding — ties the Role to the SA
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-full-access-binding
  namespace: openldap
subjects:
  - kind:      ServiceAccount
    name:      flux
    namespace: openldap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:     Role
  name:     flux-full-access

