# The ldap-bind-secrets and opencloud-ldap-secrets adminPassword have to be the same
apiVersion: v1
kind: Secret
metadata:
  name: ldap-bind-secrets
  namespace: opencloud
stringData:
  reva-ldap-bind-password: admin
---          
apiVersion: v1
kind: Secret
metadata:
  name: s3secret
  namespace: opencloud
stringData:
  accessKey: opencloud
  secretKey: opencloud-secret-key
---
# LDAP Administrator credentials
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-ldap-secrets
  namespace: opencloud
stringData:
  adminPassword: "admin"
  configPassword: "config"
---
# Keycloak Administrator credentials
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-keycloak-admin-secrets
  namespace: opencloud
stringData:
  adminPassword: "admin"
---
# Message queue configuration  
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-amqp-secret
  namespace: opencloud
stringData:
  amqpUrl: "amqp://guest:Dd0SXIe1k9osdfjkmA0TK1bb1B1d38OFSb@localhost"
---
# OnlyOffice secrets
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-onlyoffice-secrets
  namespace: opencloud
stringData:
  inbox: "Dd0SXIe1k9oCfdffgrfNmA0TK1bb1B1d38OFSb"
  outbox: "Dd0SXIe1k9oCfdffgrfNmA0TK1bb1B1d38OFSb"
  session: "Dd0SXIe1k9oCfdffgrfNmA0TK1bb1B1d38OFSb"
---
# Minio root password
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-minio-secrets
  namespace: opencloud
stringData:
  rootPassword: "opencloud-secret-key"
---
# Keycloak PostgreSQL password
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-keycloak-postgresql-secrets
  namespace: opencloud
stringData:
  postgresqlPassword: "keycloak"
